Develop
SFKhakimov/Mesto_backend pull request #2
Opened 2020-04-03 23:48 UTC by SFKhakimov

В методе createUser добавил функционал создания токена, также токен создается после авторизации (метод login)
Карточки нельзя просматривать до регистрации или авторизации.
Токен хранится в куках, в качестве ключа использовал строку сгенерированную методом crypto
Нельзя удалять не свои карточки, метод удаления ищет совпадения: по id карточки и id пользователя. 
id пользователя берется из свойства req.user. id записывается после расшифровки токена мидлварой auth.js

2020-04-04 18:11 UTC, aarefiev requested changes
Очень хорошая работа 👍 . Дополнительное задание реализовано :+1: :+1: :+1: .

Хорошее описание проект :+1:. Проект хорошо структурирован, элементы сгруппированы в группы по принадлежности (роуты, контроллеры, модели, мидлвары, модули ошибок). Для статической проверки синтаксиса подключен линтер `eslint`, устанавливающий соответствие стайлгайду _Airbnb_. Запуск линтера завершается без ошибок. Отдельного конфигурационного файла со всеми настройками для работы сервера не найдено. Схемы моделей настроены корректно. Роуты в целом настроены корректно, но есть ошибки в путях некоторых роутов плюс в некоторых есть ошибки с обработкой нештатных ситуаций. Корректно настроена централизованная обработка несуществующего роута, мидлвара авторизации. Сервер локально запускается с хот релоадом, ошибок во время работы сервера не возникает. Временные файлы игнорируются.

Большая работа была выполнена в рамках прошлой практики. В этой работе существенно меньше ошибок и меньше улучшений. Краткий список представлен ниже, расширенные комментарии представлены непосредственно в коде.

**Нужно исправить:**
1. Роуты не соответствуют заданию.
2. При удалении карточки чужого пользователя возвращается 404.
3. При регистрации возвращается пароль.
4. При регистрации пользователя пользователя автоматически авторизует.
5. При попытке зарегистрироваться с существующим `email` возвращается 500.

**Можно лучше:**
1. Вынести настройки в отдельный конфигурационный файл.
2. Использовать хелпер `.orFail()` для обработки несуществующей записи.

2020-04-04 18:11 UTC, aarefiev commented on app.js
> +app.post('/signIn', login);
Нужно исправить: роуты не соответствуют заданию.
Должны быть:
- `POST /signup`,
- `POST /signin`

2020-04-04 18:11 UTC, aarefiev commented on controllers/users.js
> +      res.cookie('jwt', token, { maxAge: 3600000 * 24 * 7, httpOnly: true }).send(user);
Нужно исправить: при регистрации возвращается пароль.
Ответ:
```json
{
    "_id": "5e88c7b09a657f9b9dec9e2f",
    "name": "username",
    "about": "something about username",
    "email": "username1@example.com",
    "password": "$2a$10$tfFw19OA2.sbt39ku32QeuxyOPXtd1Kz5zC11Hal50R0EMGn.zXkm",
    "avatar": "http://example.com/1.png",
    "__v": 0
}
```
Секретные данные не нужно возвращать в ответе. Пароль является секретными данными.

2020-04-04 18:11 UTC, aarefiev commented on controllers/users.js
> +      res.cookie('jwt', token, { maxAge: 3600000 * 24 * 7, httpOnly: true }).send(user);
Нужно исправить: при регистрации пользователя пользователя автоматически авторизует.
По заданию для авторизации должен быть отдельный роут. Во время регистрации только создается пользователь.

2020-04-04 18:11 UTC, aarefiev commented on controllers/users.js
> +      res.cookie('jwt', token, { maxAge: 3600000 * 24 * 7, httpOnly: true }).send(user);
Нужно исправить: при попытке зарегистрироваться с существующим `email` возвращается 500.
Ответ:
```json
{
    "message": "Пользователь не создан - E11000 duplicate key error collection: mestodb.users index: email_1 dup key: { email: \"username1@example.com\" }"
}
```
Ожидается: [409 Conflict](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/409).

2020-04-04 18:11 UTC, aarefiev commented on controllers/cards.js
> +  Card.findOneAndDelete({ _id: req.params.cardId, owner: req.user._id })
Нужно исправить: при удалении карточки чужого пользователя возвращается 404.
Если удаление карточки запрещено по причине блокирования доступа, то нужно возвращать [403 Forbidden](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/403). Чтобы это реализовать, нужно разделить процесс удаления на несколько запросов + обработка: поиск карточки по `id`, проверка удаления (лучше использовать метод [`.equals()`](https://mongoosejs.com/docs/api.html#document_Document-equals) для проверки равенства идентификаторов) и уже затем удаление.

2020-04-04 18:11 UTC, aarefiev commented on controllers/users.js
> +      const token = jwt.sign({ _id: user._id }, '9fff22460051528711f3ab535499a758');
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Секретный ключ.
Если оставить определение значений в коде, то возникает несколько очевидных проблем:
- изменение какой-то настройки требует изменений всех файлов, где она используется,
- нельзя использовать отдельные настройки для разработки и продакшена

Лучше создать отдельный файл (например, `config.js`) и в нём уже заполнять те настройки, которые будут использоваться в проекте (например, секретный ключ, порт сервера или адрес для подключения к базе данных). Далее этот файл подключать в тех файлах, где необходимо получить значения. Пример файла:
```js
module.exports.PORT = process.env.PORT || 3000;
```
По аналогии с примером выше добавляются и остальные настройки.

2020-04-04 18:11 UTC, aarefiev commented on models/user.js
> +      }
Можно лучше: использовать хелпер `.orFail()` для обработки несуществующей записи.

2020-04-04 18:11 UTC, aarefiev commented on middleware/auth.js
> +    payload = jwt.verify(authorization, '9fff22460051528711f3ab535499a758');
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Секретный ключ.

2020-04-04 18:11 UTC, aarefiev commented on controllers/users.js
> +      const token = jwt.sign({ _id: user._id }, '9fff22460051528711f3ab535499a758');
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Секретный ключ.

2020-04-05 22:09 UTC, SFKhakimov commented
В методе создания пользователя проверяю наличие _email_ в базе с помощью метода `findOne(`). Если пользователь есть возвращаю ошибку _409_. Убрал авторизацию пользователя при регистрации.

Перед удалением карточки сначала ищу ее по _id_, если нахожу то методом `.equals() `проверяю _id_ карточки и _id_ авторизованного пользователя, если не совпадают то выдаю ошибку _403_. Если все ок то удаляю карточку. Вернулся к методу удаления `findByIdAndDelete()`

Роуты поправил. Настройки вынес в отдельный файл.

Старался быть внимательнее, новых ошибок не нашел :)

2020-04-06 06:27 UTC, aarefiev requested changes
Отлично, внимательное изучение ошибок не подвело. Осталось совсем чуть-чуть.

**Нужно исправить:**
1. При регистрации с невалидными данными ответ не возвращается.
2. При возникновении ошибки при удалении карточки возвращается ответ в формате `HTML`.

2020-04-06 06:27 UTC, aarefiev commented on controllers/users.js
> +      bcrypt.hash(password, 10)
Нужно исправить: при регистрации с невалидными данными ответ не возвращается.
Плюс ошибка в консоли:
```bash
(node:46623) UnhandledPromiseRejectionWarning: ValidationError: user validation failed: avatar: Validator failed for path `avatar` with value `1`
    at new ValidationError (/Users/jmi/work/ya-reviews/Mesto_backend/node_modules/mongoose/lib/error/validation.js:31:11)
    at model.Document.invalidate (/Users/jmi/work/ya-reviews/Mesto_backend/node_modules/mongoose/lib/document.js:2552:32)
    at /Users/jmi/work/ya-reviews/Mesto_backend/node_modules/mongoose/lib/document.js:2374:17
    at /Users/jmi/work/ya-reviews/Mesto_backend/node_modules/mongoose/lib/schematype.js:1099:9
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:46623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:46623) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Один `.catch()` блок может обработать цепочку промисов, только если дочерний промис будет возвращен.

2020-04-06 06:27 UTC, aarefiev commented on controllers/cards.js
> +    .catch((err) => res.status(err.statusCode || 500).send(err.message));
Нужно исправить: при возникновении ошибки при удалении карточки возвращается ответ в формате `HTML`.
Ожидается `JSON`.

2020-04-06 06:27 UTC, aarefiev commented on controllers/cards.js
> +        .then((cards) => res.send(cards));
Здесь тоже потенциальная проблема, как и при регистрации. `.catch()` блок обработает исключение только если дочерний промис будет возвращен.

2020-04-06 23:11 UTC, SFKhakimov commented
- Промисы возвращаю, теперь ошибки попадают в блок `.catch()`
- Текст ошибки перевел в формат `JSON`

2020-04-07 14:08 UTC, aarefiev approved these changes
Круто, все ок 🚀 .
Ошибки исправлены, новых не обнаружено.
Работа принимается 🚀 .

2020-04-07 14:53 UTC, merged